import React from 'react';
import Head from 'next/head';
import Navbar from './Navbar';
import Footer from './Footer';

function Layout({ children }) {
	return (
		<div className='layout'>
			<Head>
				<title>E-commerce Store</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header>
				<Navbar />
			</header>
			<main className='main-container'>{children}</main>
			<footer>
				<Footer />
			</footer>
		</div>
	);
}

export default Layout;
